### ISSUE TITLE
Possible error in newly provided sample-resources files

### ISSUE THREAD

**Issue by JMelde89** [microclimate-devops/xml-language-server#16]
When opening the invoice.xsd file provided in the multiple_schemas folder in the sample resources, VS Code prompts the immediate error: "[XML]" Cannot find the declaration of element 'xsd:schema' (cvc-elt.1). (2,2).

I've had similar errors crop up in other personal XSD files, all of which use the import method for bringing in other schemas. When I delete the <xsd:import> element the error goes away (this is also true in the aforementioned sample file), but then I lose the connection between the various schemas.

**Comment by gindik** [comment]
Thanks for raising the issue, we'll investigate the problem. Could you please let us know which operating system and Java Virtual Machine you are using in your environment?

**Comment by JMelde89** [comment]
Really appreciate it - I'm running Windows 10 and the Java SE Development Kit 8u171 (x64 version). I've linked this to VS Code via the xmlLang.javaHome setting. All of the other validation appears to work just fine with respect to the sample-resources files. It's specifically when importing schemas to other XSDs that seems to be the problem. Thanks again!

**Comment by gindik** [comment]
We setup a Windows 10 64-bit environment with Java SE 8u171 (http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-windows-x64.exe) and added the following configuration:

{
    "xmlLang.javaHome": "C:\\\Program Files\\\Java\\\jre1.8.0_171"
}

Unfortunately we were not able to reproduce the problem. Opening multiple_schemas/invoice_prefix_with_errors.xml correctly shows the validation problem:

![screen](https://user-images.githubusercontent.com/17207930/41172069-ac17c5c4-6b20-11e8-85e2-cbc1c5428695.png)

**Comment by JMelde89** [comment]
Thanks Gabriel - if you open multiple_schemas/invoice.xsd does it show any validation error in your environment?

![image](https://user-images.githubusercontent.com/40043143/41172188-aedc5c46-6b18-11e8-86a9-62c99e7b3afc.png)

**Comment by gindik** [comment]
@JMelde89 thanks for the clarification. The extension handles schema based validation for XML files. Unfortunately at this time it does not handle schema based validation for XSD files. For that we would need to explore how to include the schema-for-schema in the language server. This is why basic structural errors will be surfaced (after all a schema is an XML document) but when it comes to validating the content of the XSD file, errors won't be surfaced properly.

**Comment by JMelde89** [comment]
Ah, makes sense, thanks for clarifying. Sounds like the extension may raise validation errors when viewing XSD files at the moment, because it isn't able to validate the XSD's content, but it does properly compare said schema against the associated XML instance for both structure and content when viewing the XML file. Glad to understand it isn't just a local issue to my machine - really appreciate your prompt help with this!
