### ISSUE TITLE
Do not eagerly start Language Server

### ISSUE THREAD

**Issue by gorkem** [microclimate-devops/xml-language-server#3]
`"workspaceContains:**/*.xml"` on package.xml is causing the language server to start. I do not this language server needs to be started eagerly as it does not really work on the project level but on single file.

**Comment by sghung** [comment]
Thanks for your suggestion Gorkem. I have changed the behaviour to only load the extension when the XML file is opened (instead of the existence of XML files in the workspace).

commit b76cf6043c58c1bbef550791b509613066875ad2
